name: Build Mod

on:
  push:
    branches: [ "26.1.2" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload built mod
        uses: actions/upload-artifact@v4
        with:
          name: split-screen-mod
          path: build/libs/*.jar
